openapi: 3.0.2
info:
  contact:
    email: spond@temple.edu
    url: http://github.com/veg/api-datamonkey
  description: |
    Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Datamonkey API
  version: 1.0.0
  x-logo:
    url: https://raw.githubusercontent.com/veg/datamonkey-js/refs/heads/master/public/assets/img/header-logo.svg
    altText: Datamonkey.org logo
externalDocs:
  description: Use Datamonkey today!
  url: https://datamonkey.org
servers:
- url: http://datamonkey.org/api/v1
- url: https://datamonkey.org/api/v1
tags:
- description: Examples starting jobs and fetching results for FEL
  name: FEL
- description: Examples starting jobs and fetching results for BUSTED
  name: BUSTED
- description: Examples starting jobs and fetching results for ABSREL
  name: ABSREL
- description: Examples uploading files to Datamonkey
  name: File Upload and QC
- description: Check health of Datamonkey server
  name: Health
- description: Examples building codon-aware alignments from uploaded data. Somewhere
    over the rainbow..
  name: Codon Aware Alignments
- description: Examples building phylogenetic trees from uploaded data. Somewhere
    over the rainbow..
  name: Tree Building
paths:
  /health:
    get:
      operationId: getHealth
      parameters:
      - description: Pretty print response
        explode: true
        in: query
        name: pretty_print
        required: false
        schema:
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
          description: Success
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
          description: Unable to get health. Internal server error
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
          description: Unable to get health. Service unavailable
      summary: Check health of Datamonkey
      tags:
      - Health
  /methods/fel-start:
    post:
      operationId: startFELJob
      parameters:
      - description: Pretty print response
        explode: true
        in: query
        name: pretty_print
        required: false
        schema:
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FelRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobStatus'
          description: Success
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidDataError'
          description: Unprocessable Entity
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
          description: Internal Server Error
      summary: Start and monitor a FEL job
      tags:
      - FEL
  /methods/fel-result:
    post:
      operationId: getFELJob
      parameters:
      - description: Pretty print response
        explode: true
        in: query
        name: pretty_print
        required: false
        schema:
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FelRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FelResult'
          description: Success
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
          description: Internal Server Error
      summary: Get a FEL job result
      tags:
      - FEL
  /methods/busted-start:
    post:
      operationId: startBUSTEDJob
      parameters:
      - description: Pretty print response
        explode: true
        in: query
        name: pretty_print
        required: false
        schema:
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BustedRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobStatus'
          description: Success
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidDataError'
          description: Unprocessable Entity
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
          description: Internal Server Error
      summary: Start and monitor a BUSTED job
      tags:
      - BUSTED
  /methods/busted-result:
    post:
      operationId: getBUSTEDJob
      parameters:
      - description: Pretty print response
        explode: true
        in: query
        name: pretty_print
        required: false
        schema:
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BustedRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BustedResult'
          description: Success
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
          description: Internal Server Error
      summary: Get a BUSTED job result
      tags:
      - BUSTED
  /methods/absrel-start:
    post:
      operationId: startABSRELJob
      parameters:
      - description: Pretty print response
        explode: true
        in: query
        name: pretty_print
        required: false
        schema:
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AbsrelRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobStatus'
          description: Success
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidDataError'
          description: Unprocessable Entity
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
          description: Internal Server Error
      summary: Start and monitor an ABSREL job
      tags:
      - ABSREL
  /methods/absrel-result:
    post:
      operationId: getABSRELJob
      parameters:
      - description: Pretty print response
        explode: true
        in: query
        name: pretty_print
        required: false
        schema:
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AbsrelRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AbsrelResult'
          description: Success
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
          description: Internal Server Error
      summary: Get an ABSREL job result
      tags:
      - ABSREL
  /datasets:
    get:
      operationId: getDatasetsList
      parameters:
      - description: Pretty print response
        explode: true
        in: query
        name: pretty_print
        required: false
        schema:
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Datasets'
          description: Success
      summary: Get a list of datasets uploaded to Datamonkey
      tags:
      - File Upload and QC
    post:
      operationId: PostDataset
      parameters:
      - description: Pretty print response
        explode: true
        in: query
        name: pretty_print
        required: false
        schema:
          type: boolean
        style: form
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Datasets'
          description: Success
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidDataError'
          description: Unprocessable Entity
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
          description: Internal Server Error
      summary: Upload a dataset to Datamonkey
      tags:
      - File Upload and QC
components:
  schemas:
    Status:
      enum:
      - healthy
      - unhealthy
      - unknown
      type: string
    Health:
      example:
        details:
          slurm: null
          datamonkey: null
        status: healthy
      properties:
        status:
          $ref: '#/components/schemas/Status'
        details:
          $ref: '#/components/schemas/Health_details'
      type: object
    Hash:
      pattern: "^[a-zA-Z0-9]+$"
      type: string
    GeneticCode:
      default: Universal
      description: |
        Available Genetic Codes
      enum:
      - Universal
      - Vertebrate mtDNA
      - Yeast mtDNA
      - Mold/Protozoan mtDNA
      - Invertebrate mtDNA
      - Ciliate Nuclear
      - Echinoderm mtDNA
      - Eupltoid Nuclear
      - Alt. Yeast Nuclear
      - Ascidian mtDNA
      - Flatworm mtDNA
      - Blepharisma Nuclear
      type: string
    FelRequest:
      example:
        genetic_code: Universal
        site_multihit: Estimate
        ci: false
        srv: true
        multiple_hits: None
        tree: tree
        alignment: alignment
        branches:
        - branches
        - branches
        resample: 0.8008281904610115
      properties:
        alignment:
          pattern: "^[a-zA-Z0-9]+$"
          type: string
        tree:
          pattern: "^[a-zA-Z0-9]+$"
          type: string
        ci:
          default: false
          description: Compute confidence intervals for estimated rates
          type: boolean
        srv:
          default: true
          description: Include synonymous rate variation in the model
          type: boolean
        resample:
          default: 0
          description: Number of bootstrap resamples
          type: number
        multiple_hits:
          default: None
          description: Specify handling of multiple nucleotide substitutions
          enum:
          - None
          - Double
          - Double+Triple
          type: string
        site_multihit:
          default: Estimate
          description: Specify whether to estimate multiple hit rates for each site
          enum:
          - Estimate
          - Global
          type: string
        genetic_code:
          $ref: '#/components/schemas/GeneticCode'
        branches:
          default: []
          description: "Branches to include in the analysis. If empty, all branches\
            \ are included."
          items:
            type: string
          type: array
      type: object
    JobStatus:
      example:
        error_message: error_message
        job_id: job_id
        status: queued
      properties:
        job_id:
          pattern: "^[a-zA-Z0-9]+$"
          type: string
        status:
          enum:
          - queued
          - running
          - completed
          - error
          type: string
        error_message:
          type: string
      type: object
    InvalidDataError:
      example:
        errors:
        - field: field
          message: message
        - field: field
          message: message
      properties:
        errors:
          items:
            $ref: '#/components/schemas/InvalidDataError_errors_inner'
          type: array
      type: object
    ServerError:
      example:
        code: code
        details: details
        error: error
      properties:
        error:
          description: A general description of the error.
          type: string
        code:
          description: A unique error code (if available).
          type: string
        details:
          description: Optional details about the error.
          type: string
      type: object
    Email:
      description: User email address
      example: john.smith@example.com
      format: test
      type: string
    AnalysisInfo:
      example:
        settings:
          site_filter: "{}"
        contact: john.smith@example.com
      properties:
        contact:
          description: User email address
          example: john.smith@example.com
          format: test
          type: string
        settings:
          $ref: '#/components/schemas/AnalysisInfo_settings'
      type: object
    InputInfo:
      example:
        trees:
          key: trees
      properties:
        trees:
          additionalProperties:
            type: string
          type: object
      type: object
    TestedBranchesInfo:
      additionalProperties:
        additionalProperties:
          enum:
          - tested
          - background
          type: string
        type: object
      type: object
    TimersInfo:
      items:
        properties: {}
        type: object
      type: array
    PartitionsInfo:
      additionalProperties:
        $ref: '#/components/schemas/PartitionsInfo_value'
      type: object
    BaseResponse:
      properties:
        analysis:
          $ref: '#/components/schemas/AnalysisInfo'
        input:
          $ref: '#/components/schemas/InputInfo'
        tested:
          additionalProperties:
            additionalProperties:
              enum:
              - tested
              - background
              type: string
            type: object
          type: object
        timers:
          items:
            properties: {}
            type: object
          type: array
        runtime:
          pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
          type: string
        data partitions:
          additionalProperties:
            $ref: '#/components/schemas/PartitionsInfo_value'
          type: object
      type: object
    FelResult:
      example:
        result:
          input:
            trees:
              key: trees
          timers:
          - "{}"
          - "{}"
          data partitions:
            key:
              coverage:
              - 0
              - 0
              name: name
          branch attributes:
            attributes:
              key:
                display order: 2
                attribute type: attribute type
            additionalProperties:
              key:
                Global MG94xREV: 9.301444243932576
                Nucleotide GTR: 3.616076749251911
                original name: original name
          tested:
            key:
              key: tested
          MLE:
            headers:
            - - headers
              - headers
            - - headers
              - headers
            content:
              key:
              - - 4.145608029883936
                - 4.145608029883936
              - - 4.145608029883936
                - 4.145608029883936
          runtime: runtime
          analysis:
            settings:
              site_filter: "{}"
            contact: john.smith@example.com
          fits:
            key:
              Log Likelihood: 5.962133916683182
              estimated parameters: 7.061401241503109
              Rate Distributions:
                key:
                - - 5.637376656633329
                  - 5.637376656633329
                - - 5.637376656633329
                  - 5.637376656633329
              AIC-c: 6.027456183070403
              display order: 2.3021358869347655
              Equilibrium frequencies:
              - - 1.4658129805029452
                - 1.4658129805029452
              - - 1.4658129805029452
                - 1.4658129805029452
        job_id: job_id
      properties:
        job_id:
          pattern: "^[a-zA-Z0-9]+$"
          type: string
        result:
          $ref: '#/components/schemas/FelResult_result'
      type: object
    BustedRequest:
      example:
        genetic_code: Universal
        srv: "Yes"
        syn_rates: 6
        multiple_hits: None
        rates: 1
        tree: tree
        grid_size: 1
        alignment: alignment
        branches:
        - branches
        - branches
        starting_points: 1
        error_sink: false
      properties:
        alignment:
          pattern: "^[a-zA-Z0-9]+$"
          type: string
        tree:
          pattern: "^[a-zA-Z0-9]+$"
          type: string
        srv:
          default: "Yes"
          description: Include synonymous rate variation in the model
          enum:
          - "Yes"
          - "No"
          - branch-site
          type: string
        multiple_hits:
          default: None
          description: Specify handling of multiple nucleotide substitutions
          enum:
          - None
          - Double
          - Double+Triple
          type: string
        genetic_code:
          $ref: '#/components/schemas/GeneticCode'
        branches:
          default: []
          description: "Branches to include in the analysis. If empty, all branches\
            \ are included."
          items:
            type: string
          type: array
        rates:
          default: 3
          description: The number omega rate classes to include in the model
          maximum: 10
          minimum: 1
          type: integer
        syn_rates:
          default: 3
          description: The number synonymous rate classes to include in the model
          maximum: 10
          minimum: 1
          type: integer
        grid_size:
          default: 250
          description: The number of points in the initial distributional guess for
            likelihood fitting
          minimum: 1
          type: integer
        starting_points:
          default: 1
          description: The number of initial random guesses to seed rate values optimization
          minimum: 1
          type: integer
        error_sink:
          default: false
          description: An advanced experimental setting; include a rate class to capture
            misalignment artifacts
          type: boolean
      type: object
    BustedResult:
      example:
        result:
          timers:
          - "{}"
          - "{}"
          test results:
            p-value: 7.457744773683766
            LRT: 6.84685269835264
          tested:
            key:
              key: tested
          Evidence Ratios:
            optimized null:
            - - 6.683562403749608
              - 6.683562403749608
            - - 6.683562403749608
              - 6.683562403749608
            constrained:
            - - 9.369310271410669
              - 9.369310271410669
            - - 9.369310271410669
              - 9.369310271410669
          runtime: runtime
          analysis:
            settings:
              site_filter: "{}"
            contact: john.smith@example.com
          fits:
            key:
              Log Likelihood: 1.4658129805029452
              estimated parameters: 3.616076749251911
              Rate Distributions:
                Test:
                  key:
                    proportion: 5.637376656633329
                    omega: 5.962133916683182
                Synonymous site-to-site rates:
                  key:
                    proportion: 2.3021358869347655
                    rate: 7.061401241503109
              AIC-c: 6.027456183070403
              display order: 9.301444243932576
          Synonymous site-posteriors:
          - - 1.1730742509559433
            - 1.1730742509559433
          - - 1.1730742509559433
            - 1.1730742509559433
          input:
            trees:
              key: trees
          data partitions:
            key:
              coverage:
              - 0
              - 0
              name: name
          branch attributes:
            attributes:
              key:
                display order: 2
                attribute type: attribute type
            additionalProperties:
              key:
                Posterior prob omega class:
                - - 7.386281948385884
                  - 7.386281948385884
                - - 7.386281948385884
                  - 7.386281948385884
                Posterior prob omega class by site:
                - - 1.2315135367772556
                  - 1.2315135367772556
                - - 1.2315135367772556
                  - 1.2315135367772556
                Nucleotide GTR: 4.145608029883936
                MG94xREV with separate rates for branch sets: 2.027123023002322
                original name: original name
                constrained: 1.0246457001441578
                unconstrained: 1.4894159098541704
          substitutions:
            key:
              key:
                root: root
          background: 0.8008281904610115
          Site Log Likelihood:
            optimized null:
            - - 9.965781217890562
              - 9.965781217890562
            - - 9.965781217890562
              - 9.965781217890562
            constrained:
            - - 4.965218492984954
              - 4.965218492984954
            - - 4.965218492984954
              - 4.965218492984954
            unconstrained:
            - - 5.025004791520295
              - 5.025004791520295
            - - 5.025004791520295
              - 5.025004791520295
        job_id: job_id
      properties:
        job_id:
          pattern: "^[a-zA-Z0-9]+$"
          type: string
        result:
          $ref: '#/components/schemas/BustedResult_result'
      type: object
    AbsrelRequest:
      example:
        genetic_code: Universal
        srv: true
        multiple_hits: None
        tree: tree
        blb: 0.08008281904610115
        alignment: alignment
        branches:
        - branches
        - branches
      properties:
        alignment:
          pattern: "^[a-zA-Z0-9]+$"
          type: string
        tree:
          pattern: "^[a-zA-Z0-9]+$"
          type: string
        srv:
          default: true
          description: Include synonymous rate variation in the model
          type: boolean
        multiple_hits:
          default: None
          description: Specify handling of multiple nucleotide substitutions
          enum:
          - None
          - Double
          - Double+Triple
          type: string
        genetic_code:
          $ref: '#/components/schemas/GeneticCode'
        branches:
          default: []
          description: "Branches to include in the analysis. If empty, all branches\
            \ are included."
          items:
            type: string
          type: array
        blb:
          default: 1
          description: Bag of little bootstrap alignment resampling rate
          maximum: 1
          minimum: 0
          type: number
      type: object
    AbsrelResult:
      example:
        result:
          input:
            trees:
              key: trees
          timers:
            key:
              timer: 6
              order: 8
          data partitions:
            key:
              coverage:
              - - 1
                - 1
              - - 1
                - 1
              name: name
          test results:
            tested: 4
            P-value threshold: 2.027123023002322
            positive test results: 7
          branch attributes:
            attributes:
              key:
                display order: 2
                attribute type: attribute type
            additionalProperties:
              key:
                Uncorrected P-value: 9.965781217890562
                Full adaptive model: 1.1730742509559433
                Baseline MG94xREV: 1.4894159098541704
                Rate Distributions:
                - - 4.965218492984954
                  - 4.965218492984954
                - - 4.965218492984954
                  - 4.965218492984954
                Nucleotide GTR: 1.0246457001441578
                Baseline MG94xREV omega ratio: 6.84685269835264
                Rate classes: 7
                Corrected P-value: 9.369310271410669
                original name: original name
                LRT: 5.025004791520295
          tested:
            key:
              key: tested
          runtime: runtime
          analysis:
            settings:
              site_filter: "{}"
            contact: john.smith@example.com
          fits:
            key:
              Log Likelihood: 6.027456183070403
              estimated parameters: 9.301444243932576
              Rate Distributions:
                key:
                  Mean: 1.4658129805029452
                  Median: 5.962133916683182
                  "2.5%": 5.637376656633329
                  "97.5%": 2.3021358869347655
              AIC-c: 0.8008281904610115
              display order: 7.061401241503109
              Equilibrium frequencies:
              - - 3.616076749251911
                - 3.616076749251911
              - - 3.616076749251911
                - 3.616076749251911
        job_id: job_id
      properties:
        job_id:
          pattern: "^[a-zA-Z0-9]+$"
          type: string
        result:
          $ref: '#/components/schemas/AbsrelResult_result'
      type: object
    DatasetMeta:
      properties:
        name:
          type: string
        description:
          type: string
        type:
          type: string
      type: object
    Dataset:
      allOf:
      - $ref: '#/components/schemas/DatasetMeta'
      - properties:
          id:
            $ref: '#/components/schemas/Hash'
          created:
            format: date-time
            type: string
          updated:
            format: date-time
            type: string
        type: object
      example:
        created: 2000-01-23T04:56:07.000+00:00
        name: name
        description: description
        id: null
        type: type
        updated: 2000-01-23T04:56:07.000+00:00
      type: object
    Datasets:
      example:
        datasets:
        - created: 2000-01-23T04:56:07.000+00:00
          name: name
          description: description
          id: null
          type: type
          updated: 2000-01-23T04:56:07.000+00:00
        - created: 2000-01-23T04:56:07.000+00:00
          name: name
          description: description
          id: null
          type: type
          updated: 2000-01-23T04:56:07.000+00:00
      properties:
        datasets:
          items:
            $ref: '#/components/schemas/Dataset'
          type: array
      type: object
    UploadRequest:
      properties:
        meta:
          $ref: '#/components/schemas/DatasetMeta'
        file:
          description: Dataset File. incompatible with the url field
          format: binary
          type: string
        url:
          description: URL of the file to upload. incompatible with the file field
          type: string
      type: object
    Health_details:
      example:
        slurm: null
        datamonkey: null
      properties:
        slurm:
          $ref: '#/components/schemas/Status'
        datamonkey:
          $ref: '#/components/schemas/Status'
      type: object
    InvalidDataError_errors_inner:
      example:
        field: field
        message: message
      properties:
        field:
          description: The field that caused the error
          type: string
        message:
          description: The error message
          type: string
      type: object
    AnalysisInfo_settings:
      example:
        site_filter: "{}"
      properties:
        site_filter:
          properties: {}
          type: object
      type: object
    PartitionsInfo_value:
      example:
        coverage:
        - 0
        - 0
        name: name
      properties:
        name:
          type: string
        coverage:
          items:
            type: integer
          type: array
      type: object
    FelResult_result_allOf_fits_value:
      example:
        Log Likelihood: 5.962133916683182
        estimated parameters: 7.061401241503109
        Rate Distributions:
          key:
          - - 5.637376656633329
            - 5.637376656633329
          - - 5.637376656633329
            - 5.637376656633329
        AIC-c: 6.027456183070403
        display order: 2.3021358869347655
        Equilibrium frequencies:
        - - 1.4658129805029452
          - 1.4658129805029452
        - - 1.4658129805029452
          - 1.4658129805029452
      properties:
        AIC-c:
          type: number
        Equilibrium frequencies:
          items:
            items:
              type: number
            type: array
          type: array
        Log Likelihood:
          type: number
        Rate Distributions:
          additionalProperties:
            items:
              items:
                type: number
              type: array
            type: array
          type: object
        display order:
          type: number
        estimated parameters:
          type: number
      type: object
    FelResult_result_allOf_branch_attributes_additionalProperties_value:
      example:
        Global MG94xREV: 9.301444243932576
        Nucleotide GTR: 3.616076749251911
        original name: original name
      properties:
        Global MG94xREV:
          type: number
        Nucleotide GTR:
          type: number
        original name:
          type: string
      type: object
    FelResult_result_allOf_branch_attributes_attributes_value:
      example:
        display order: 2
        attribute type: attribute type
      properties:
        attribute type:
          type: string
        display order:
          type: integer
      type: object
    FelResult_result_allOf_branch_attributes:
      example:
        attributes:
          key:
            display order: 2
            attribute type: attribute type
        additionalProperties:
          key:
            Global MG94xREV: 9.301444243932576
            Nucleotide GTR: 3.616076749251911
            original name: original name
      properties:
        additionalProperties:
          additionalProperties:
            $ref: '#/components/schemas/FelResult_result_allOf_branch_attributes_additionalProperties_value'
          type: object
        attributes:
          additionalProperties:
            $ref: '#/components/schemas/FelResult_result_allOf_branch_attributes_attributes_value'
          type: object
      type: object
    FelResult_result_allOf_MLE:
      example:
        headers:
        - - headers
          - headers
        - - headers
          - headers
        content:
          key:
          - - 4.145608029883936
            - 4.145608029883936
          - - 4.145608029883936
            - 4.145608029883936
      properties:
        headers:
          items:
            items:
              type: string
            type: array
          type: array
        content:
          additionalProperties:
            items:
              items:
                type: number
              type: array
            type: array
          type: object
      type: object
    FelResult_result:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - properties:
          fits:
            additionalProperties:
              $ref: '#/components/schemas/FelResult_result_allOf_fits_value'
            type: object
          branch attributes:
            $ref: '#/components/schemas/FelResult_result_allOf_branch_attributes'
          MLE:
            $ref: '#/components/schemas/FelResult_result_allOf_MLE'
        type: object
      example:
        input:
          trees:
            key: trees
        timers:
        - "{}"
        - "{}"
        data partitions:
          key:
            coverage:
            - 0
            - 0
            name: name
        branch attributes:
          attributes:
            key:
              display order: 2
              attribute type: attribute type
          additionalProperties:
            key:
              Global MG94xREV: 9.301444243932576
              Nucleotide GTR: 3.616076749251911
              original name: original name
        tested:
          key:
            key: tested
        MLE:
          headers:
          - - headers
            - headers
          - - headers
            - headers
          content:
            key:
            - - 4.145608029883936
              - 4.145608029883936
            - - 4.145608029883936
              - 4.145608029883936
        runtime: runtime
        analysis:
          settings:
            site_filter: "{}"
          contact: john.smith@example.com
        fits:
          key:
            Log Likelihood: 5.962133916683182
            estimated parameters: 7.061401241503109
            Rate Distributions:
              key:
              - - 5.637376656633329
                - 5.637376656633329
              - - 5.637376656633329
                - 5.637376656633329
            AIC-c: 6.027456183070403
            display order: 2.3021358869347655
            Equilibrium frequencies:
            - - 1.4658129805029452
              - 1.4658129805029452
            - - 1.4658129805029452
              - 1.4658129805029452
    BustedResult_result_allOf_fits_value_Rate_Distributions_Test_value:
      example:
        proportion: 5.637376656633329
        omega: 5.962133916683182
      properties:
        omega:
          type: number
        proportion:
          type: number
      type: object
    BustedResult_result_allOf_fits_value_Rate_Distributions_Synonymous_site_to_site_rates_value:
      example:
        proportion: 2.3021358869347655
        rate: 7.061401241503109
      properties:
        proportion:
          type: number
        rate:
          type: number
      type: object
    BustedResult_result_allOf_fits_value_Rate_Distributions:
      example:
        Test:
          key:
            proportion: 5.637376656633329
            omega: 5.962133916683182
        Synonymous site-to-site rates:
          key:
            proportion: 2.3021358869347655
            rate: 7.061401241503109
      properties:
        Test:
          additionalProperties:
            $ref: '#/components/schemas/BustedResult_result_allOf_fits_value_Rate_Distributions_Test_value'
          type: object
        Synonymous site-to-site rates:
          additionalProperties:
            $ref: '#/components/schemas/BustedResult_result_allOf_fits_value_Rate_Distributions_Synonymous_site_to_site_rates_value'
          type: object
      type: object
    BustedResult_result_allOf_fits_value:
      example:
        Log Likelihood: 1.4658129805029452
        estimated parameters: 3.616076749251911
        Rate Distributions:
          Test:
            key:
              proportion: 5.637376656633329
              omega: 5.962133916683182
          Synonymous site-to-site rates:
            key:
              proportion: 2.3021358869347655
              rate: 7.061401241503109
        AIC-c: 6.027456183070403
        display order: 9.301444243932576
      properties:
        AIC-c:
          type: number
        Log Likelihood:
          type: number
        Rate Distributions:
          $ref: '#/components/schemas/BustedResult_result_allOf_fits_value_Rate_Distributions'
        display order:
          type: number
        estimated parameters:
          type: number
      type: object
    BustedResult_result_allOf_branch_attributes_additionalProperties_value:
      example:
        Posterior prob omega class:
        - - 7.386281948385884
          - 7.386281948385884
        - - 7.386281948385884
          - 7.386281948385884
        Posterior prob omega class by site:
        - - 1.2315135367772556
          - 1.2315135367772556
        - - 1.2315135367772556
          - 1.2315135367772556
        Nucleotide GTR: 4.145608029883936
        MG94xREV with separate rates for branch sets: 2.027123023002322
        original name: original name
        constrained: 1.0246457001441578
        unconstrained: 1.4894159098541704
      properties:
        MG94xREV with separate rates for branch sets:
          type: number
        Nucleotide GTR:
          type: number
        Posterior prob omega class:
          items:
            items:
              type: number
            type: array
          type: array
        Posterior prob omega class by site:
          items:
            items:
              type: number
            type: array
          type: array
        constrained:
          type: number
        original name:
          type: string
        unconstrained:
          type: number
      type: object
    BustedResult_result_allOf_branch_attributes:
      example:
        attributes:
          key:
            display order: 2
            attribute type: attribute type
        additionalProperties:
          key:
            Posterior prob omega class:
            - - 7.386281948385884
              - 7.386281948385884
            - - 7.386281948385884
              - 7.386281948385884
            Posterior prob omega class by site:
            - - 1.2315135367772556
              - 1.2315135367772556
            - - 1.2315135367772556
              - 1.2315135367772556
            Nucleotide GTR: 4.145608029883936
            MG94xREV with separate rates for branch sets: 2.027123023002322
            original name: original name
            constrained: 1.0246457001441578
            unconstrained: 1.4894159098541704
      properties:
        additionalProperties:
          additionalProperties:
            $ref: '#/components/schemas/BustedResult_result_allOf_branch_attributes_additionalProperties_value'
          type: object
        attributes:
          additionalProperties:
            $ref: '#/components/schemas/FelResult_result_allOf_branch_attributes_attributes_value'
          type: object
      type: object
    BustedResult_result_allOf_test_results:
      example:
        p-value: 7.457744773683766
        LRT: 6.84685269835264
      properties:
        LRT:
          type: number
        p-value:
          type: number
      type: object
    BustedResult_result_allOf_substitutions_value_value:
      additionalProperties:
        type: string
      example:
        root: root
      properties:
        root:
          type: string
      type: object
    BustedResult_result_allOf_Site_Log_Likelihood:
      example:
        optimized null:
        - - 9.965781217890562
          - 9.965781217890562
        - - 9.965781217890562
          - 9.965781217890562
        constrained:
        - - 4.965218492984954
          - 4.965218492984954
        - - 4.965218492984954
          - 4.965218492984954
        unconstrained:
        - - 5.025004791520295
          - 5.025004791520295
        - - 5.025004791520295
          - 5.025004791520295
      properties:
        constrained:
          items:
            items:
              type: number
            type: array
          type: array
        unconstrained:
          items:
            items:
              type: number
            type: array
          type: array
        optimized null:
          items:
            items:
              type: number
            type: array
          type: array
      type: object
    BustedResult_result_allOf_Evidence_Ratios:
      example:
        optimized null:
        - - 6.683562403749608
          - 6.683562403749608
        - - 6.683562403749608
          - 6.683562403749608
        constrained:
        - - 9.369310271410669
          - 9.369310271410669
        - - 9.369310271410669
          - 9.369310271410669
      properties:
        constrained:
          items:
            items:
              type: number
            type: array
          type: array
        optimized null:
          items:
            items:
              type: number
            type: array
          type: array
      type: object
    BustedResult_result:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - properties:
          background:
            type: number
          fits:
            additionalProperties:
              $ref: '#/components/schemas/BustedResult_result_allOf_fits_value'
            type: object
          branch attributes:
            $ref: '#/components/schemas/BustedResult_result_allOf_branch_attributes'
          test results:
            $ref: '#/components/schemas/BustedResult_result_allOf_test_results'
          substitutions:
            additionalProperties:
              additionalProperties:
                $ref: '#/components/schemas/BustedResult_result_allOf_substitutions_value_value'
              type: object
            type: object
          Synonymous site-posteriors:
            items:
              items:
                type: number
              type: array
            type: array
          Site Log Likelihood:
            $ref: '#/components/schemas/BustedResult_result_allOf_Site_Log_Likelihood'
          Evidence Ratios:
            $ref: '#/components/schemas/BustedResult_result_allOf_Evidence_Ratios'
        type: object
      example:
        timers:
        - "{}"
        - "{}"
        test results:
          p-value: 7.457744773683766
          LRT: 6.84685269835264
        tested:
          key:
            key: tested
        Evidence Ratios:
          optimized null:
          - - 6.683562403749608
            - 6.683562403749608
          - - 6.683562403749608
            - 6.683562403749608
          constrained:
          - - 9.369310271410669
            - 9.369310271410669
          - - 9.369310271410669
            - 9.369310271410669
        runtime: runtime
        analysis:
          settings:
            site_filter: "{}"
          contact: john.smith@example.com
        fits:
          key:
            Log Likelihood: 1.4658129805029452
            estimated parameters: 3.616076749251911
            Rate Distributions:
              Test:
                key:
                  proportion: 5.637376656633329
                  omega: 5.962133916683182
              Synonymous site-to-site rates:
                key:
                  proportion: 2.3021358869347655
                  rate: 7.061401241503109
            AIC-c: 6.027456183070403
            display order: 9.301444243932576
        Synonymous site-posteriors:
        - - 1.1730742509559433
          - 1.1730742509559433
        - - 1.1730742509559433
          - 1.1730742509559433
        input:
          trees:
            key: trees
        data partitions:
          key:
            coverage:
            - 0
            - 0
            name: name
        branch attributes:
          attributes:
            key:
              display order: 2
              attribute type: attribute type
          additionalProperties:
            key:
              Posterior prob omega class:
              - - 7.386281948385884
                - 7.386281948385884
              - - 7.386281948385884
                - 7.386281948385884
              Posterior prob omega class by site:
              - - 1.2315135367772556
                - 1.2315135367772556
              - - 1.2315135367772556
                - 1.2315135367772556
              Nucleotide GTR: 4.145608029883936
              MG94xREV with separate rates for branch sets: 2.027123023002322
              original name: original name
              constrained: 1.0246457001441578
              unconstrained: 1.4894159098541704
        substitutions:
          key:
            key:
              root: root
        background: 0.8008281904610115
        Site Log Likelihood:
          optimized null:
          - - 9.965781217890562
            - 9.965781217890562
          - - 9.965781217890562
            - 9.965781217890562
          constrained:
          - - 4.965218492984954
            - 4.965218492984954
          - - 4.965218492984954
            - 4.965218492984954
          unconstrained:
          - - 5.025004791520295
            - 5.025004791520295
          - - 5.025004791520295
            - 5.025004791520295
    AbsrelResult_result_allOf_fits_value_Rate_Distributions_value:
      example:
        Mean: 1.4658129805029452
        Median: 5.962133916683182
        "2.5%": 5.637376656633329
        "97.5%": 2.3021358869347655
      properties:
        Mean:
          type: number
        Median:
          type: number
        "2.5%":
          type: number
        "97.5%":
          type: number
      type: object
    AbsrelResult_result_allOf_fits_value:
      example:
        Log Likelihood: 6.027456183070403
        estimated parameters: 9.301444243932576
        Rate Distributions:
          key:
            Mean: 1.4658129805029452
            Median: 5.962133916683182
            "2.5%": 5.637376656633329
            "97.5%": 2.3021358869347655
        AIC-c: 0.8008281904610115
        display order: 7.061401241503109
        Equilibrium frequencies:
        - - 3.616076749251911
          - 3.616076749251911
        - - 3.616076749251911
          - 3.616076749251911
      properties:
        AIC-c:
          type: number
        Log Likelihood:
          type: number
        Rate Distributions:
          additionalProperties:
            $ref: '#/components/schemas/AbsrelResult_result_allOf_fits_value_Rate_Distributions_value'
          type: object
        display order:
          type: number
        estimated parameters:
          type: number
        Equilibrium frequencies:
          items:
            items:
              type: number
            type: array
          type: array
      type: object
    AbsrelResult_result_allOf_test_results:
      example:
        tested: 4
        P-value threshold: 2.027123023002322
        positive test results: 7
      properties:
        P-value threshold:
          type: number
        tested:
          type: integer
        positive test results:
          type: integer
      type: object
    AbsrelResult_result_allOf_data_partitions_value:
      example:
        coverage:
        - - 1
          - 1
        - - 1
          - 1
        name: name
      properties:
        name:
          type: string
        coverage:
          items:
            items:
              type: integer
            type: array
          type: array
      type: object
    AbsrelResult_result_allOf_branch_attributes_additionalProperties_value:
      example:
        Uncorrected P-value: 9.965781217890562
        Full adaptive model: 1.1730742509559433
        Baseline MG94xREV: 1.4894159098541704
        Rate Distributions:
        - - 4.965218492984954
          - 4.965218492984954
        - - 4.965218492984954
          - 4.965218492984954
        Nucleotide GTR: 1.0246457001441578
        Baseline MG94xREV omega ratio: 6.84685269835264
        Rate classes: 7
        Corrected P-value: 9.369310271410669
        original name: original name
        LRT: 5.025004791520295
      properties:
        original name:
          type: string
        Nucleotide GTR:
          type: number
        Baseline MG94xREV:
          type: number
        Baseline MG94xREV omega ratio:
          type: number
        Rate classes:
          type: integer
        Full adaptive model:
          type: number
        Rate Distributions:
          items:
            items:
              type: number
            type: array
          type: array
        LRT:
          type: number
        Uncorrected P-value:
          type: number
        Corrected P-value:
          type: number
      type: object
    AbsrelResult_result_allOf_branch_attributes:
      example:
        attributes:
          key:
            display order: 2
            attribute type: attribute type
        additionalProperties:
          key:
            Uncorrected P-value: 9.965781217890562
            Full adaptive model: 1.1730742509559433
            Baseline MG94xREV: 1.4894159098541704
            Rate Distributions:
            - - 4.965218492984954
              - 4.965218492984954
            - - 4.965218492984954
              - 4.965218492984954
            Nucleotide GTR: 1.0246457001441578
            Baseline MG94xREV omega ratio: 6.84685269835264
            Rate classes: 7
            Corrected P-value: 9.369310271410669
            original name: original name
            LRT: 5.025004791520295
      properties:
        additionalProperties:
          additionalProperties:
            $ref: '#/components/schemas/AbsrelResult_result_allOf_branch_attributes_additionalProperties_value'
          type: object
        attributes:
          additionalProperties:
            $ref: '#/components/schemas/FelResult_result_allOf_branch_attributes_attributes_value'
          type: object
      type: object
    AbsrelResult_result_allOf_timers_value:
      example:
        timer: 6
        order: 8
      properties:
        timer:
          type: integer
        order:
          type: integer
      type: object
    AbsrelResult_result:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - properties:
          fits:
            additionalProperties:
              $ref: '#/components/schemas/AbsrelResult_result_allOf_fits_value'
            type: object
          test results:
            $ref: '#/components/schemas/AbsrelResult_result_allOf_test_results'
          tested:
            additionalProperties:
              additionalProperties:
                type: string
              type: object
            type: object
          data partitions:
            additionalProperties:
              $ref: '#/components/schemas/AbsrelResult_result_allOf_data_partitions_value'
            type: object
          branch attributes:
            $ref: '#/components/schemas/AbsrelResult_result_allOf_branch_attributes'
          timers:
            additionalProperties:
              $ref: '#/components/schemas/AbsrelResult_result_allOf_timers_value'
            type: object
        type: object
      example:
        input:
          trees:
            key: trees
        timers:
          key:
            timer: 6
            order: 8
        data partitions:
          key:
            coverage:
            - - 1
              - 1
            - - 1
              - 1
            name: name
        test results:
          tested: 4
          P-value threshold: 2.027123023002322
          positive test results: 7
        branch attributes:
          attributes:
            key:
              display order: 2
              attribute type: attribute type
          additionalProperties:
            key:
              Uncorrected P-value: 9.965781217890562
              Full adaptive model: 1.1730742509559433
              Baseline MG94xREV: 1.4894159098541704
              Rate Distributions:
              - - 4.965218492984954
                - 4.965218492984954
              - - 4.965218492984954
                - 4.965218492984954
              Nucleotide GTR: 1.0246457001441578
              Baseline MG94xREV omega ratio: 6.84685269835264
              Rate classes: 7
              Corrected P-value: 9.369310271410669
              original name: original name
              LRT: 5.025004791520295
        tested:
          key:
            key: tested
        runtime: runtime
        analysis:
          settings:
            site_filter: "{}"
          contact: john.smith@example.com
        fits:
          key:
            Log Likelihood: 6.027456183070403
            estimated parameters: 9.301444243932576
            Rate Distributions:
              key:
                Mean: 1.4658129805029452
                Median: 5.962133916683182
                "2.5%": 5.637376656633329
                "97.5%": 2.3021358869347655
            AIC-c: 0.8008281904610115
            display order: 7.061401241503109
            Equilibrium frequencies:
            - - 3.616076749251911
              - 3.616076749251911
            - - 3.616076749251911
              - 3.616076749251911
